version: "3"
services:
  goflet:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./goflet-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always